# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  print-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello!"

  print-helloworld:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print-helloworld:
          requires:
            - "print-hello"