# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

workflows:
  test-environment-var:
    jobs:
      - print-environment-var
      
jobs:
  print-environment-var:
    docker:
      - image: cimg/base:2023.06
    Steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $Udacity_Nm_Var 
